# Generated by Django 5.1.2 on 2024-10-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_criar_dispositivos_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='texto_hashtag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
