# Generated by Django 5.1.2 on 2024-10-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hashtag_texto_hashtag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtag_Postagem',
            new_name='HashtagPostagem',
        ),
        migrations.RenameModel(
            old_name='Midia_Postagem',
            new_name='MidiaPostagem',
        ),
        migrations.RenameModel(
            old_name='Midia_Repostagem',
            new_name='MidiaRepostagem',
        ),
    ]
