# Generated by Django 5.1.2 on 2024-10-27 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_hashtagpostagem_hashtag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curtida',
            new_name='CurtidaPostagem',
        ),
        migrations.CreateModel(
            name='CurtidaRepostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_curtida', models.DateTimeField(auto_now_add=True)),
                ('repostagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repostagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
