# Generated by Django 5.1.2 on 2024-10-27 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_curtida_curtidapostagem_curtidarepostagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='repostagem',
            name='dispositivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dispositivo'),
        ),
    ]
