# Generated by Django 5.1.2 on 2024-10-27 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_texto_repostagem_texto_repostagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repostagem',
            name='repostagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repostagem_repostagem', to='api.repostagem'),
        ),
    ]
