# Generated by Django 5.1.2 on 2024-10-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_midiarepostagem_postagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midiapostagem',
            name='midia',
            field=models.ImageField(upload_to=''),
        ),
    ]
